name: yassin_store_app
description: A modern online store app for Yassin-store.com
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  woocommerce_api: ^1.0.2
  provider: ^6.0.0
  flutter_local_notifications: ^9.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
